In [1]:
import pandas as pd
import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

In [2]:
df = pd.read_csv(r"D:\EXCELR OFFLINE\Python\NLP\IMDB DATASET.csv")

df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
#Convert Text to Lowercase
df['review'] = df['review'].str.lower()

df['review'].head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production. <br /><br />the...
2    i thought this was a wonderful way to spend ti...
3    basically there's a family where a little boy ...
4    petter mattei's "love in the time of money" is...
Name: review, dtype: object

In [4]:
#Remove HTML Tags and URLs
df['review'] = df['review'].apply(
    lambda x: re.sub(r'<.*?>|https?://\S+|www\.\S+', '', str(x))
)

df['review'].head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production. the filming tec...
2    i thought this was a wonderful way to spend ti...
3    basically there's a family where a little boy ...
4    petter mattei's "love in the time of money" is...
Name: review, dtype: object

In [5]:
#Remove Punctuation and Special Character
df['review'] = df['review'].apply(
    lambda x: re.sub(r'[^a-zA-Z0-9\s]', '', x)
)

df['review'].head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production the filming tech...
2    i thought this was a wonderful way to spend ti...
3    basically theres a family where a little boy j...
4    petter matteis love in the time of money is a ...
Name: review, dtype: object

In [6]:
chat_words = {
    "u": "you",
    "ur": "your",
    "btw": "by the way",
    "gr8": "great",
    "pls": "please"
}

df['review'] = df['review'].apply(
    lambda x: ' '.join(chat_words.get(word, word)
                       for word in x.split())
)

df['review'].head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production the filming tech...
2    i thought this was a wonderful way to spend ti...
3    basically theres a family where a little boy j...
4    petter matteis love in the time of money is a ...
Name: review, dtype: object

In [7]:
#Remove Stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

df['review'] = df['review'].apply(
    lambda x: ' '.join(
        word for word in x.split()
        if word not in stop_words
    )
)

df['review'].head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Mahaveer/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

0    one reviewers mentioned watching 1 oz episode ...
1    wonderful little production filming technique ...
2    thought wonderful way spend time hot summer we...
3    basically theres family little boy jake thinks...
4    petter matteis love time money visually stunni...
Name: review, dtype: object

In [8]:
#Tokenization
nltk.download('punkt_tab')

df['tokens'] = df['review'].apply(word_tokenize)

df[['review', 'tokens']].head()

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Mahaveer/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

,review,tokens
0,one reviewers mentioned watching 1 oz episode ...,"[one, reviewers, mentioned, watching, 1, oz, e..."
1,wonderful little production filming technique ...,"[wonderful, little, production, filming, techn..."
2,thought wonderful way spend time hot summer we...,"[thought, wonderful, way, spend, time, hot, su..."
3,basically theres family little boy jake thinks...,"[basically, theres, family, little, boy, jake,..."
4,petter matteis love time money visually stunni...,"[petter, matteis, love, time, money, visually,..."

In [10]:
stemmer = PorterStemmer()

df['stemmed'] = df['tokens'].apply(
    lambda words: [stemmer.stem(word) for word in words]
)

df[['tokens', 'stemmed']].head()

,tokens,stemmed
0,"[one, reviewers, mentioned, watching, 1, oz, e...","[one, review, mention, watch, 1, oz, episod, y..."
1,"[wonderful, little, production, filming, techn...","[wonder, littl, product, film, techniqu, unass..."
2,"[thought, wonderful, way, spend, time, hot, su...","[thought, wonder, way, spend, time, hot, summe..."
3,"[basically, theres, family, little, boy, jake,...","[basic, there, famili, littl, boy, jake, think..."
4,"[petter, matteis, love, time, money, visually,...","[petter, mattei, love, time, money, visual, st..."

In [11]:
nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

df['lemmatized'] = df['tokens'].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words]
)

df[['tokens', 'lemmatized']].head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Mahaveer/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Mahaveer/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

,tokens,lemmatized
0,"[one, reviewers, mentioned, watching, 1, oz, e...","[one, reviewer, mentioned, watching, 1, oz, ep..."
1,"[wonderful, little, production, filming, techn...","[wonderful, little, production, filming, techn..."
2,"[thought, wonderful, way, spend, time, hot, su...","[thought, wonderful, way, spend, time, hot, su..."
3,"[basically, theres, family, little, boy, jake,...","[basically, there, family, little, boy, jake, ..."
4,"[petter, matteis, love, time, money, visually,...","[petter, matteis, love, time, money, visually,..."

In [12]:
df[['review', 'tokens', 'stemmed', 'lemmatized']].head()

,review,tokens,stemmed,lemmatized
0,one reviewers mentioned watching 1 oz episode ...,"[one, reviewers, mentioned, watching, 1, oz, e...","[one, review, mention, watch, 1, oz, episod, y...","[one, reviewer, mentioned, watching, 1, oz, ep..."
1,wonderful little production filming technique ...,"[wonderful, little, production, filming, techn...","[wonder, littl, product, film, techniqu, unass...","[wonderful, little, production, filming, techn..."
2,thought wonderful way spend time hot summer we...,"[thought, wonderful, way, spend, time, hot, su...","[thought, wonder, way, spend, time, hot, summe...","[thought, wonderful, way, spend, time, hot, su..."
3,basically theres family little boy jake thinks...,"[basically, theres, family, little, boy, jake,...","[basic, there, famili, littl, boy, jake, think...","[basically, there, family, little, boy, jake, ..."
4,petter matteis love time money visually stunni...,"[petter, matteis, love, time, money, visually,...","[petter, mattei, love, time, money, visual, st...","[petter, matteis, love, time, money, visually,..."